compute_engine_instance:
  image_project: cirrus-images
  image: family/docker-builder
  platform: linux
  cpu: 8
  memory: 16G

task:
  env:
    matrix:
      - distro: openwrt-22.03

  check_buildenv_script: |
    df -h .
    printenv

  install_depends_script: |
    apt update -y
    DEBIAN_FRONTEND=noninteractive apt install -y git ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev sudo \
    libfuse-dev

  update_submodules_script: |
    git submodule update --recursive --remote --init
    if [[ x"$distro" == x"openwrt-23.05" ]]; then
      # checkout openwrt tag
      pushd openwrt-23.05
      git checkout v23.05.0
      popd
    elif [[ x"$distro" == x"openwrt-22.03" ]]; then
      # checkout openwrt tag
      pushd openwrt-22.03
      git checkout v22.03.5
      popd
    fi
    git clone https://github.com/vernesong/OpenClash.git --depth=1 package/luci-app-openclash
    ls package/ | xargs -i sh -c 'ln -sfv $(realpath package/{}) ${distro}/package/'
    ls -lh ${distro}/package/

  prepare_packages_script: |
    # install po2lmo for openclash
    pushd package/luci-app-openclash/luci-app-openclash/tools/po2lmo
    make && sudo make install
    popd

  mkconfig_script: |
    pushd ${distro}
    ./scripts/feeds update -a
    ./scripts/feeds install -a
    cp -v ../x86_${distro}.config .config
    make defconfig
    popd

  config_artifacts:
    path: "*/.config*"

  build_image_script: |
    pushd ${distro}
    make download -j24
    FORCE_UNSAFE_CONFIGURE=1 make -j8
    popd

  images_artifacts:
    path: "*/bin/targets/x86/64/openwrt-x86-64-generic-ext4*.gz"
