container:
  image: debian:bullseye-slim
  cpu: 8
  memory: 16G

task:
  env:
    matrix:
      - distro: lede
      - distro: openwrt

  check_buildenv_script: |
    df -h .
    printenv

  update_submodules_script: |
    apt update -y
    apt install -y git
    git submodule update --recursive --remote --init


  install_depends_script: |
    apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev sudo

  prepare_packages_script: |
    ls package/ | xargs -i sh -c 'ln -sfv $(realpath package/{}) ${distro}/package/'
    ls -lh ${distro}/package/
    # install po2lmo for openclash
    pushd package/luci-app-openclash/luci-app-openclash/tools/po2lmo
    make && sudo make install
    popd

  mkconfig_script: |
    pushd ${distro}
    ./scripts/feeds update -a
    ./scripts/feeds install -a
    cp -v ../x86_${distro}.config .config
    make defconfig
    popd

  config_artifacts:
    path: "*/.config*"

  build_image_script: |
    pushd ${distro}
    make download -j24
    FORCE_UNSAFE_CONFIGURE=1 make -j8 V=s
    popd

  images_artifacts:
    path: "*/bin/targets/x86/64/openwrt*.gz"
